name: Build .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        if [[ $IS_PRERELEASE ]]
        then
          dotnet build --no-restore --configuration Release -p:VersionSuffix=$IS_PRERELEASE
        else
          dotnet build --no-restore --configuration Release
        fi
      env:
        IS_PRERELEASE: ${{ github.ref != 'refs/heads/main' && github.sha || '' }}
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Publish tool to GitHub registry if new version number
      if: ${{ github.ref != 'refs/heads/main' }}
      run: dotnet nuget push ./**/bin/Release/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json --skip-duplicate --no-symbols
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish tool to NuGet registry if new version number
      if: ${{ github.ref == 'refs/heads/main' }}
      run: dotnet nuget push ./**/bin/Release/*.nupkg -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}